cd build
# customdevice 与 withrocm 不能共存
cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_CUSTOM_DEVICE=OFF  -DWITH_DISTRIBUTE=OFF -DWITH_ONEDNN=OFF  -DWITH_GPU=OFF -DWITH_ROCM=ON -DWITH_CINN=ON -DCINN_WITH_HIP=OFF -DCINN_WITH_SYCL=ON -DPY_VERSION=3.10 -DWITH_TESTING=OFF -DCMAKE_CXX_FLAGS="-Wno-error -w"
make -j 32
